// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module "vue" {
  export interface GlobalComponents {
    Application: typeof import("./src/components/Application/Application.vue")["default"];
    HelloWorld: typeof import("./src/components/HelloWorld.vue")["default"];
    LoadingContent: typeof import("./src/components/Application/LoadingContent.vue")["default"];
    MessageContent: typeof import("./src/components/Application/MessageContent.vue")["default"];
    NButton: typeof import("naive-ui")["NButton"];
    NConfigProvider: typeof import("naive-ui")["NConfigProvider"];
    NDialogProvider: typeof import("naive-ui")["NDialogProvider"];
    NForm: typeof import("naive-ui")["NForm"];
    NFormItem: typeof import("naive-ui")["NFormItem"];
    NInput: typeof import("naive-ui")["NInput"];
    NLoadingBarProvider: typeof import("naive-ui")["NLoadingBarProvider"];
    NMessageProvider: typeof import("naive-ui")["NMessageProvider"];
    NNotificationProvider: typeof import("naive-ui")["NNotificationProvider"];
    NSelect: typeof import("naive-ui")["NSelect"];
    SwitchLanguage: typeof import("./src/components/SwitchLanguage.vue")["default"];
  }
}

export {};
